name: SkyblockCore
version: '${project.version}'
main: net.sujal.SkyblockCore
api-version: '1.21'
authors: [ Sujal ]
description: A Hypixel Skyblock inspired core stats system.

commands:
  stats:
    description: Open your stats profile GUI.
    aliases: [profile, mystats]
  sbadmin:
    description: Developer commands for SkyblockCore.
    permission: skyblockcore.admin
    
