package net.sujal.stats;

public enum StatType {
    HEALTH, MAX_HEALTH, DEFENSE, STRENGTH, CRIT_CHANCE, CRIT_DAMAGE, 
    ATTACK_SPEED, FEROCITY, INTELLIGENCE, SPEED, TRUE_DEFENSE, VITALITY, SWING_RANGE,
    MAGIC_FIND, PET_LUCK, SEA_CREATURE_CHANCE, MINING_SPEED, MINING_FORTUNE, 
    FARMING_FORTUNE, FORAGING_FORTUNE, COMBAT_WISDOM, MINING_WISDOM, FARMING_WISDOM, 
    FORAGING_WISDOM, ALCHEMY_WISDOM, ENCHANTING_WISDOM, CARPENTRY_WISDOM, TAMING_WISDOM,
    ABILITY_DAMAGE, HEALTH_REGEN, MANA_REGEN, TRUE_DAMAGE, KNOCKBACK_RESISTANCE
}
